---
- name: Make sure we have bzip2.
  apt:
    name: bzip2
    state: present

- name: Create the monero home directory
  file:
    path: /opt/monero
    state: directory
    mode: 0755

- name: Copy up monerod
  copy:
    src: monerod
    dest: /opt/monero/monerod
    owner: root
    group: root
    mode: 0755

- name: Copy over the service file
  template:
    src: monero-node.service.j2
    dest: /etc/systemd/system/monero-node.service
    owner: root
    group: root
    mode: 0644

- name: Start the daemon
  systemd:
    name: monero-node
    state: restarted
    daemon_reload: yes
