---
- name: Make sure we have bzip2.
  apt:
    name: bzip2
    state: present

- name: Create the monero data directory.
  file:
    path: /opt/monero-data/
    state: directory
    mode: 0755

- name: Get the monero daemon.
  unarchive:
    src: "https://downloads.getmonero.org/cli/monero-linux-x64-{{ monero_node_version }}.tar.bz2"
    dest: /opt/
    remote_src: yes

- name: Copy over the service file.
  template:
    src: monerod.service.j2
    dest: /etc/systemd/system/monerod.service
    owner: root
    group: root
    mode: 0644

- name: Start the daemon.
  systemd:
    name: monerod
    state: restarted
    daemon_reload: yes
